# theme: jekyll-theme-cayman
remote_theme: pages-themes/primer@v0.2.0
show_downloads: true

lang: ja

title: はじめてのJekyll + GitHub Pages
description: JekyllとGitHub Pagesを使って静的ウェブサイトを作る

collections:
  chapters:
    output: true

exclude:
  - README.md
